# Generated by Django 4.1.7 on 2023-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockedclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('path', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
