# Generated by Django 4.1.7 on 2023-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedclient',
            name='client_ip',
            field=models.CharField(max_length=100),
        ),
    ]
