# Generated by Django 4.1.7 on 2023-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blockedclient_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedclient',
            name='client_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
